# Generated by Django 5.0.14 on 2026-09-05 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2)),
                ('total_days', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='learning.studyplan')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='DayVocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_carry_over', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_days', to='content.vocabulary')),
                ('study_plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='learning.studyplanday')),
            ],
        ),
        migrations.CreateModel(
            name='DayGrammar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_carry_over', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_days', to='content.grammar')),
                ('study_plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammars', to='learning.studyplanday')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studyplanday',
            constraint=models.UniqueConstraint(fields=('study_plan', 'day_number'), name='unique_study_plan_day_number'),
        ),
        migrations.AddConstraint(
            model_name='studyplanday',
            constraint=models.UniqueConstraint(fields=('study_plan', 'date'), name='unique_study_plan_day_date'),
        ),
        migrations.AddConstraint(
            model_name='dayvocabulary',
            constraint=models.UniqueConstraint(fields=('study_plan_day', 'vocabulary'), name='unique_day_vocabulary'),
        ),
        migrations.AddConstraint(
            model_name='daygrammar',
            constraint=models.UniqueConstraint(fields=('study_plan_day', 'grammar'), name='unique_day_grammar'),
        ),
    ]
