# Generated by Django 5.0.14 on 2026-09-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daygrammar',
            name='is_carry_over',
        ),
        migrations.RemoveField(
            model_name='dayvocabulary',
            name='is_carry_over',
        ),
    ]
