# Generated by Django 5.0.14 on 2026-08-30 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern', models.CharField(max_length=200)),
                ('meaning', models.TextField()),
                ('level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2)),
                ('example', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('upload', 'Upload'), ('review', 'Review'), ('accepted', 'Accepted')], default='upload', max_length=20)),
                ('sources', models.ManyToManyField(blank=True, related_name='grammars', to='content.source')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kanji', models.CharField(max_length=100)),
                ('hiragana', models.CharField(max_length=100)),
                ('han_viet', models.CharField(blank=True, max_length=100)),
                ('meaning', models.TextField()),
                ('word_type', models.CharField(choices=[('noun', 'Danh từ'), ('verb', 'Động từ'), ('adjective', 'Tính từ')], max_length=20)),
                ('level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2)),
                ('example', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('upload', 'Upload'), ('review', 'Review'), ('accepted', 'Accepted')], default='upload', max_length=20)),
                ('sources', models.ManyToManyField(blank=True, related_name='vocabularies', to='content.source')),
                ('synonyms', models.ManyToManyField(blank=True, to='content.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_type', models.CharField(choices=[('dictionary', 'Dictionary'), ('masu', 'ます形'), ('nai', 'ない形'), ('ta', 'た形'), ('te', 'て形'), ('nakatta', 'なかった形'), ('potential', '可能形'), ('passive', '受身形'), ('causative', '使役形'), ('imperative', '命令形')], max_length=30)),
                ('value', models.CharField(max_length=100)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='content.vocabulary')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vocabularyform',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'form_type'), name='unique_vocabulary_form_type'),
        ),
    ]
