# Generated by Django 5.0.14 on 2026-09-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='word_type',
            field=models.CharField(choices=[('noun', 'Danh từ'), ('verb_1', 'Động từ nhóm 1'), ('verb_2', 'Động từ nhóm 2'), ('verb_3', 'Động từ nhóm 3'), ('adjective', 'Tính từ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vocabularyform',
            name='form_type',
            field=models.CharField(choices=[('Từ điển', '辞書'), ('Lịch sự', '丁寧'), ('Phủ định', '未然'), ('Quá khứ', 'た形'), ('te', 'て形'), ('Khả năng', '可能'), ('Thụ động', '受身'), ('Sai khiến', '使役'), ('Sai khiến thụ động', '使役受身'), ('Mệnh lệnh', '命令'), ('Ý chí', '意向'), ('Cấm chỉ', '禁止'), ('Điều kiện', '条件')], max_length=30),
        ),
    ]
