# Generated by Django 5.0.14 on 2026-09-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_vocabulary_word_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularyform',
            name='form_type',
            field=models.CharField(choices=[('suru', '辞書'), ('masu', '丁寧'), ('nai', '未然'), ('ta', 'た形'), ('te', 'て形'), ('kano', '可能'), ('ukemi', '受身'), ('shieki', '使役'), ('shieki_ukemi', '使役受身'), ('imperative', '命令'), ('ikou', '意向'), ('kenshi', '禁止'), ('jiouken', '条件')], max_length=30),
        ),
    ]
