# Generated by Django 5.0.14 on 2026-09-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_vocabularyform_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
