# Generated by Django 5.0.14 on 2026-09-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_vocabularyform_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='word_type',
            field=models.CharField(choices=[('noun', 'Danh từ'), ('verb_1', 'Động từ nhóm 1'), ('verb_2', 'Động từ nhóm 2'), ('verb_3', 'Động từ nhóm 3'), ('adjective', 'Tính từ'), ('adverb', 'Trạng từ')], max_length=20),
        ),
    ]
