# Generated by Django 5.0.14 on 2026-09-29 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0006_alter_vocabulary_word_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('document', 'Document'), ('book', 'Book'), ('other', 'Other')], default='pdf', max_length=20)),
                ('level', models.CharField(blank=True, choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2)),
                ('language', models.CharField(default='ja', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upload', 'Upload'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='upload', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('lesson_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='materials.learningmaterial')),
            ],
            options={
                'ordering': ['lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('section_type', models.CharField(choices=[('text', 'Text'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('dialogue', 'Dialogue'), ('reading', 'Reading'), ('exercise', 'Exercise'), ('explanation', 'Explanation'), ('note', 'Note'), ('table', 'Table'), ('image', 'Image'), ('custom', 'Custom')], default='text', max_length=30)),
                ('order', models.PositiveIntegerField()),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grammar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_sections', to='content.grammar')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='materials.materiallesson')),
                ('vocabulary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_sections', to='content.vocabulary')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_materials', to='materials.learningmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMaterialLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='materials.materiallesson')),
                ('user_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='materials.usermaterial')),
            ],
            options={
                'ordering': ['lesson__lesson_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='materiallesson',
            constraint=models.UniqueConstraint(fields=('material', 'lesson_number'), name='unique_material_lesson_number'),
        ),
        migrations.AddConstraint(
            model_name='materialsection',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='unique_material_section_order'),
        ),
        migrations.AddConstraint(
            model_name='usermaterial',
            constraint=models.UniqueConstraint(fields=('user', 'material'), name='unique_user_material'),
        ),
        migrations.AddConstraint(
            model_name='usermateriallesson',
            constraint=models.UniqueConstraint(fields=('user_material', 'lesson'), name='unique_user_material_lesson'),
        ),
    ]
