# Generated by Django 5.0.14 on 2026-10-03 02:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowingVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(default='ja', max_length=20)),
                ('level', models.CharField(blank=True, default='', max_length=20)),
                ('video_file', models.FileField(upload_to='shadowing/videos/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='shadowing/audio/')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upload', 'Upload'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='upload', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShadowingSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.TextField()),
                ('reading', models.TextField(blank=True, default='')),
                ('speaker', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='shadowing.shadowingvideo')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='shadowingsegment',
            constraint=models.UniqueConstraint(fields=('video', 'sequence'), name='unique_shadowing_segment_video_sequence'),
        ),
        migrations.AddConstraint(
            model_name='shadowingsegment',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gte', models.F('start_time'))), name='shadowing_segment_end_gte_start'),
        ),
    ]
