# Generated by Django 5.0.14 on 2026-10-03 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShadowingVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shadowing_videos', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_videos', to='shadowing.shadowingvideo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserShadowingSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='shadowing.shadowingsegment')),
                ('user_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_progress', to='shadowing.usershadowingvideo')),
            ],
            options={
                'ordering': ['segment__sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='usershadowingvideo',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='unique_user_shadowing_video'),
        ),
        migrations.AddConstraint(
            model_name='usershadowingsegment',
            constraint=models.UniqueConstraint(fields=('user_video', 'segment'), name='unique_user_shadowing_segment'),
        ),
    ]
